// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kWsMjK7xB47LtjfssqRijH
// Component: xXAHk0ueYHdeW
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_ishaanbedi_in.module.css"; // plasmic-import: kWsMjK7xB47LtjfssqRijH/projectcss
import sty from "./PlasmicCopyableLink.module.css"; // plasmic-import: xXAHk0ueYHdeW/css

export type PlasmicCopyableLink__VariantMembers = {};
export type PlasmicCopyableLink__VariantsArgs = {};
type VariantPropType = keyof PlasmicCopyableLink__VariantsArgs;
export const PlasmicCopyableLink__VariantProps = new Array<VariantPropType>();

export type PlasmicCopyableLink__ArgsType = {
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicCopyableLink__ArgsType;
export const PlasmicCopyableLink__ArgProps = new Array<ArgPropType>("children");

export type PlasmicCopyableLink__OverridesType = {
  root?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
  link?: p.Flex<"a"> & Partial<LinkProps>;
  freeBox?: p.Flex<"div">;
  text?: p.Flex<"div">;
};

export interface DefaultCopyableLinkProps {
  children?: React.ReactNode;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicCopyableLink__RenderFunc(props: {
  variants: PlasmicCopyableLink__VariantsArgs;
  args: PlasmicCopyableLink__ArgsType;
  overrides: PlasmicCopyableLink__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      {true ? (
        <p.PlasmicImg
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img)}
          displayHeight={"16px" as const}
          displayMaxHeight={"none" as const}
          displayMaxWidth={"none" as const}
          displayMinHeight={"0" as const}
          displayMinWidth={"0" as const}
          displayWidth={"12px" as const}
          src={
            "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCAxMiAxNiIgaGVpZ2h0PSIxNiIgd2lkdGg9IjEyIj4KPHBhdGggZmlsbD0iI0ZBRkFGQSIgZD0iTTEwLjA1MjEgMTUuMjM5Nkg1Ljk3OTAyQzUuNjI2NDQgMTUuMjM5NiA1LjM0MDYxIDE0Ljk1MzcgNS4zNDA2MSAxNC42MDEyQzUuMzQwNjEgMTQuMjQ4NiA1LjYyNjQ0IDEzLjk2MjcgNS45NzkwMiAxMy45NjI3SDEwLjA1MjFDMTAuMjcxNyAxMy45NjI4IDEwLjQ1MDggMTMuNzg2NiAxMC40NTQzIDEzLjU2NjlWNi4yMTg4M0MxMC40NTQxIDYuMTEzNzggMTAuNDEyOSA2LjAxMjk2IDEwLjMzOTQgNS45Mzc5M0w4LjM1MzkxIDMuOTUyNDdDOC4yNzkyNiAzLjg3ODM2IDguMTc4MTkgMy44MzcwMiA4LjA3MzAxIDMuODM3NTZINC40NzIzN0M0LjI1Mjc0IDMuODQxMDQgNC4wNzY1MyA0LjAyMDEgNC4wNzY1NiA0LjIzOTc1VjE0LjYxMzlDNC4wNzY1NiAxNC45NjY1IDMuNzkwNzMgMTUuMjUyMyAzLjQzODE1IDE1LjI1MjNDMy4wODU1NiAxNS4yNTIzIDIuNzk5NzQgMTQuOTY2NSAyLjc5OTc0IDE0LjYxMzlWNC4yMzk3NUMyLjgwMzI1IDMuMzE0OTUgMy41NTM5NSAyLjU2NzExIDQuNDc4NzYgMi41NjcxMkg4LjA3OTM5QzguNTI1MDEgMi41NjU2IDguOTUyNjggMi43NDI2NCA5LjI2NjgzIDMuMDU4N0wxMS4yNTIzIDUuMDQ0MTVDMTEuNTY2NiA1LjM1OTUgMTEuNzQzMyA1Ljc4NjM5IDExLjc0MzkgNi4yMzE2VjEzLjU3OTdDMTEuNzMzMyAxNC41MDQ1IDEwLjk3NjkgMTUuMjQ2NyAxMC4wNTIxIDE1LjIzOTZaTTEuNTE2NTMgMTIuMDQ2OFYxLjY3MjY0QzEuNTIwMDIgMS40NTMgMS42OTkwNyAxLjI3Njc5IDEuOTE4NzMgMS4yNzY4Mkg2LjE1Nzc3QzYuNTEwMzYgMS4yNzY4MiA2Ljc5NjE5IDAuOTkwOTk1IDYuNzk2MTkgMC42Mzg0MTFDNi43OTYxOSAwLjI4NTgyNiA2LjUxMDM2IDAgNi4xNTc3NyAwSDEuOTE4NzNDMC45OTM5MjYgMC4wMDM1MTYzOSAwLjI0NjA4NyAwLjc1NDIxIDAuMjQ2MDk0IDEuNjc5MDJWMTIuMDUzMkMwLjI0NjA5NCAxMi40MDU4IDAuNTMxOTIgMTIuNjkxNiAwLjg4NDUwNCAxMi42OTE2QzEuMjM3MDkgMTIuNjkxNiAxLjUyMjkxIDEyLjQwNTggMS41MjI5MSAxMi4wNTMyTDEuNTE2NTMgMTIuMDQ2OFoiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZmlsbC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=" as const
          }
        />
      ) : null}

      <p.PlasmicLink
        data-plasmic-name={"link"}
        data-plasmic-override={overrides.link}
        className={classNames(projectcss.all, projectcss.a, sty.link)}
        component={Link}
        href={"mailto:careers@narative.co" as const}
        platform={"nextjs"}
      >
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox)}
        >
          {p.renderPlasmicSlot({
            defaultContents: "hi@ishaanbedi.in",
            value: args.children,
            className: classNames(sty.slotTargetChildren)
          })}
        </div>
      </p.PlasmicLink>

      {true ? (
        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text
          )}
        >
          {"copied"}
        </div>
      ) : null}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "link", "freeBox", "text"],
  img: ["img"],
  link: ["link", "freeBox"],
  freeBox: ["freeBox"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof p.PlasmicImg;
  link: "a";
  freeBox: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCopyableLink__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCopyableLink__VariantsArgs;
    args?: PlasmicCopyableLink__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCopyableLink__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCopyableLink__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicCopyableLink__ArgProps,
          internalVariantPropNames: PlasmicCopyableLink__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicCopyableLink__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCopyableLink";
  } else {
    func.displayName = `PlasmicCopyableLink.${nodeName}`;
  }
  return func;
}

export const PlasmicCopyableLink = Object.assign(
  // Top-level PlasmicCopyableLink renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    link: makeNodeComponent("link"),
    freeBox: makeNodeComponent("freeBox"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicCopyableLink
    internalVariantProps: PlasmicCopyableLink__VariantProps,
    internalArgProps: PlasmicCopyableLink__ArgProps
  }
);

export default PlasmicCopyableLink;
/* prettier-ignore-end */
